Q1 Combining a one and a two-dimensional NumPy Array

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Q2 Flatten a 2d numpy array into 1d array

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()

print(flat)

[1 2 3 4 5 6]


Q3 Reverse a numpy array

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reverse = arr[::-1]

print(reverse)

[50 40 30 20 10]


Q4 Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy

In [4]:
import numpy as np

# max and min in an array
arr = np.array([12, 45, 67, 23, 89, 10])

print("Maximum =", np.max(arr))
print("Minimum =", np.min(arr))


# No of rows and columns in an array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

rows, cols = arr.shape

print("Rows =", rows)
print("Columns =", cols)

# Selecting elements from an array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("All Elements:")
print(arr)

print("Specific Element:")
print(arr[1, 1])


# finding sum of values in array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

total = 0

for row in arr:
    for value in row:
        total += value

print("Sum =", total)


# performing arithmetic operations on array
a = np.array([10, 20, 30])

b = np.array([2, 4, 5])

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)



Maximum = 89
Minimum = 10
Rows = 2
Columns = 3
All Elements:
[[10 20 30]
 [40 50 60]]
Specific Element:
50
Sum = 21
Addition = [12 24 35]
Subtraction = [ 8 16 25]
Multiplication = [ 20  80 150]
Division = [5. 5. 6.]


Q5 Iterate 3D array using for loop and nditer 

In [5]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Using For Loop")

for x in arr:
    for y in x:
        for z in y:
            print(z)

print("\nUsing nditer")

for x in np.nditer(arr):
    print(x)

Using For Loop
1
2
3
4
5
6
7
8

Using nditer
1
2
3
4
5
6
7
8


Q6 Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

In [6]:
import numpy as np
from scipy import stats
arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

avg = (arr1 + arr2) / 2

print("Average of NumPy Arrays:")
print(avg)

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

combined = np.concatenate((arr1, arr2))

print("Mean =", np.mean(combined))
print("Median =", np.median(combined))
print("Mode =", stats.mode(combined, axis=None).mode)

Average of NumPy Arrays:
[2. 2.]
Mean = 6.5
Median = 6.5
Mode = 1
