Q1 Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 

In [1]:
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

print("Original Array:")
print(arr)

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0:")
print(arr)

# Interchange rows and columns
transpose_arr = arr.T

print("\nTranspose Array:")
print(transpose_arr)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After Replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Transpose Array:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


Q2 Move axes of 3D array to new positions

In [2]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

print("Original Shape:")
print(arr.shape)

# Move axis 0 to position 2
new_arr = np.moveaxis(arr, 0, 2)

print("\nNew Shape:")
print(new_arr.shape)

print("\nArray after moving axes:")
print(new_arr)

Original Shape:
(2, 3, 4)

New Shape:
(3, 4, 2)

Array after moving axes:
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


Q3 Replace NaN values with average of columns 

In [3]:
import numpy as np

arr = np.array([[10, np.nan, 30],
                [20, 40, np.nan],
                [30, 50, 60]])

print("Original Array:")
print(arr)

# Column means
col_mean = np.nanmean(arr, axis=0)

# Find NaN positions
inds = np.where(np.isnan(arr))

# Replace NaN with column mean
arr[inds] = np.take(col_mean, inds[1])

print("\nAfter Replacing NaN with Column Mean:")
print(arr)

Original Array:
[[10. nan 30.]
 [20. 40. nan]
 [30. 50. 60.]]

After Replacing NaN with Column Mean:
[[10. 45. 30.]
 [20. 40. 45.]
 [30. 50. 60.]]


Q4 Replace negative value with zero in numpy array using replace

In [4]:
import numpy as np

arr = np.array([10, -5, 20, -8, 15, -3])

print("Original Array:")
print(arr)

arr[arr < 0] = 0

print("\nAfter Replacing Negative Values with 0:")
print(arr)

Original Array:
[10 -5 20 -8 15 -3]

After Replacing Negative Values with 0:
[10  0 20  0 15  0]
