Q1 Create numpy array and perform following operation 
1)  Convert 1D array to 2D 
2) Print Array Attributes(Like shape, dimenssion, data type, itemsize) 
3) Create a 3×3 NumPy array of all 9 
4) Create a 1D array of 10 evenly spaced values between 25 and 125 
5) Convert a Python list into a NumPy array 
6) Reverse a 1D NumPy array 
7) Create a 4×4×3 array and extract value at its second set, first row and last column 
8) Create a 4×4 and Extract Odd Rows and Even Columns 
9) Slice the first two rows and first two columns of econd set from a 4×4×3 array 
10) Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] 
11) Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 
12) Perform arithmetic operations on two NumPy arrays element-wise Add two NumPy arrays element by element. Multiply two NumPy arrays element by element. 
13) Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] arr2 = [10,40,37]

In [4]:
import numpy as np

# Create a 1D array with 6 elements
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape it to a 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)


print("\n*********************************************")

# Using the 2D array created above
print("Shape:", arr_2d.shape)
print("Dimension:", arr_2d.ndim)
print("Data type:", arr_2d.dtype)
print("Itemsize (in bytes):", arr_2d.itemsize)

print("\n*********************************************")

arr_all_9 = np.full((3, 3), 9)
print(arr_all_9)


print("\n*********************************************")

arr_spaced = np.linspace(25, 125, 10)
print(arr_spaced)


print("\n*********************************************")

py_list = [10, 20, 30, 40]
arr_from_list = np.array(py_list)

print("Python List:", py_list)
print("NumPy Array:", arr_from_list)


print("\n*********************************************")

arr_to_reverse = np.array([1, 2, 3, 4, 5])
reversed_arr = arr_to_reverse[::-1]

print("Original:", arr_to_reverse)
print("Reversed:", reversed_arr)


print("\n*********************************************")

# Create a 4x4x3 array with numbers from 0 to 47
arr_3d = np.arange(4 * 4 * 3).reshape(4, 4, 3)

# Extract value at 2nd set (index 1), 1st row (index 0), last column (index -1)
extracted_val = arr_3d[1, 0, -1]

print("Value extracted:", extracted_val)


print("\n*********************************************")

arr_4x4 = np.arange(16).reshape(4, 4)
print("Original 4x4 Array:\n", arr_4x4)

# Slice: rows 1 and 3, columns 0 and 2
extracted_section = arr_4x4[1::2, 0::2]
print("\nExtracted Array (Odd rows & Even columns):\n", extracted_section)


print("\n*********************************************")

# Using the same arr_3d from step 7
# 2nd set -> index 1 | First two rows -> 0:2 | First two columns -> 0:2
sliced_3d = arr_3d[1, 0:2, 0:2]
print("Sliced 2x2 section from second set:\n", sliced_3d)


print("\n*********************************************")
arr_elements = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])
print("Before:\n", arr_elements)

# Loop through rows and columns to find and replace odd values
for i in range(arr_elements.shape[0]):
    for j in range(arr_elements.shape[1]):
        if arr_elements[i, j] % 2 != 0:
            arr_elements[i, j] = -1

print("\nAfter replacing odd numbers with -1:\n", arr_elements)

print("\n*********************************************")


arr_nonzero = np.array([1, 0, 2, 0, 3, 0, 4])
indices = np.nonzero(arr_nonzero)

print("Indices of non-zero elements:", indices[0])


print("\n*********************************************")

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Element-wise addition
add_res = x + y

# Element-wise multiplication
mult_res = x * y

print("Addition:", add_res)
print("Multiplication:", mult_res)

print("\n*********************************************")

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

# Compute dot product: (15*10) + (20*40) + (25*37)
dot_product = np.dot(arr1, arr2)

print("Dot Product:", dot_product)


1D Array: [1 2 3 4 5 6]
2D Array:
 [[1 2 3]
 [4 5 6]]

*********************************************
Shape: (2, 3)
Dimension: 2
Data type: int64
Itemsize (in bytes): 8

*********************************************
[[9 9 9]
 [9 9 9]
 [9 9 9]]

*********************************************
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

*********************************************
Python List: [10, 20, 30, 40]
NumPy Array: [10 20 30 40]

*********************************************
Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]

*********************************************
Value extracted: 14

*********************************************
Original 4x4 Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted Array (Odd rows & Even columns):
 [[ 4  6]
 [12 14]]

*********************************************
Sliced 2x2 section from second set:
 [[12 13]
 [15 16]]

******************